# Generated by Django 4.2.7 on 2023-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='video',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/%Y%m%d%H%M%S/'),
        ),
    ]
